name: Check

on:
  pull_request: {}
  push:
    branches: master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run cargo check
        run: cargo check --workspace --locked
      - name: Run cargo check --no-default-features
        run: cargo check --workspace --locked --no-default-features
      - name: Run cargo check --all-features
        run: cargo check --workspace --locked --all-features
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
      - name: Check format
        run: cargo fmt -- --check
